### ISSUE TITLE
Multiple Groups

### ISSUE THREAD

**Issue by gvenka008c** [lukaspustina/dynamic-inventory-for-ansible-with-openstack#11]
Hi,

I tried setting multiple group names using nova meta tag as below but couldn't get that working. Can you please suggest?
# nova meta hostname set "group=mesos_masters"
# ansible -i inventory/openstack.py mesos_masters -m ping

b9d2e61e | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
# nova meta hostname set "group=mesos_masters,consul_bootstrap"
# ansible -i inventory/openstack.py mesos_masters -m ping

 [WARNING]: provided hosts list is empty, only localhost is available

Thanks,
Govind

**Comment by lukaspustina** [comment]
What's the output of running `inventory/openstack.py`?

**Comment by gvenka008c** [comment]
@lukaspustina For some reason it is not taking the group as separate when using comma as a delimiter.

```
          "metadata": {
            "ansible_host_groups": "consul_bootstrap", 
            "cluster_name": "jenkins_mesos_master", 
            "group": "mesos_masters,consul_servers", 
            "master_count": "1", 
            "myid": "1"
          }, 
```

```
  "mesos_masters,consul_servers": [
    "ca8c9fc7-337f-4f92-baac-", 
    "a904e509-b4b1-479e-8137-"
  ], 
```

**Comment by lukaspustina** [comment]
It's difficult to diagnose, when you send only partial output. But you do know that the script parses metadata key `ansible_host_groups` and does not parse metadata key `group`?

**Comment by gvenka008c** [comment]
@lukaspustina I tried using anise_host_groups key as well but didn't get any output.

```
$ ansible -i inventory/openstack.py consul_bootstrap -m ping
 [WARNING]: provided hosts list is empty, only localhost is available
```

```
  "meta-ansible_host_groups_consul_bootstrap": [
    "b9d2e61e-0653-4a1f-a472-"
  ], 
```

**Comment by lukaspustina** [comment]
Again, it's very difficult to help you without knowing the meta data and the output of the script.

Please send me the _full_ output of `nova show <your instance> | grep meta` and `inventory/openstack.py`.

**Comment by gvenka008c** [comment]
@lukaspustina 

```
nova show <servername> | grep meta
| metadata                             | {"cluster_name": "jenkins_mesos_master", "myid": "1", "master_count": "1", "group": "mesos_masters,consul_bootstrap", "ansible_host_groups": "consul_bootstrap"} |
```

Is there any specific set of information that you are looking in output of openstack.py? Here is some snippet of it

```
          "interface_ip": "xx.xxx.xxx.xx", 
          "key_name": "keynote", 
          "metadata": {
            "cluster_name": "jenkins_mesos_master", 
            "group": "mesos_masters,consul_servers", 
            "master_count": "3", 
            "myid": "3"
          }, 


  "mesos_masters,consul_bootstrap": [
    "b9d2e61e-0653-4a1f-a472-"
  ], 

  "meta-group_mesos_masters,consul_bootstrap": [
    "b9d2e61e-0653-4a1f-a472-"
  ], 

```

I am not sure if we can give different group names using "," comma as a delimiter

```
            "group": "mesos_masters,consul_servers", 
```

**Comment by lukaspustina** [comment]
Okay, let's turn this around. So for one of my instances the meta data look like this when retrieved by `nova show <instance>`:

``````
| metadata                               | {"ansible_host_vars": "has_data_volume->True;zabbix_host_metadata->host_class=admin-inf", "ansible_host_groups": "virtual_infrastructure_hosts,admin_v_infrastructure,apt_repos,apt_caches,ntp_servers"}```
``````

And the output generated by openstack.py looks like this:

```
{
    "admin_v_infrastructure": {
        "hosts": [
            "10.102.8.109"
        ]
    },
    "_meta": {
        "hostvars": {
            "10.102.8.109": {
                "dns_server_for_domains": [
                    "v.clusterb.centerdevice.local",
                    "infrastructure.v.clusterb.centerdevice.local"
                ],
                "has_data_volume": "True",
                "os_hostname": "admin01",
                "zabbix_host_metadata": "host_class=admin-inf"
            }
        }
    },
    "ntp_servers": {
        "hosts": [
            "10.102.8.109"
        ]
    },
    "apt_caches": {
        "hosts": [
            "10.102.8.109"
        ]
    },
    "apt_repos": {
        "hosts": [
            "10.102.8.109"
        ]
    },
    "virtual_infrastructure_hosts": {
        "hosts": [
            "10.102.8.109"
        ]
    }
}
```

As you can see the host `admin01` is part of several ansible groups and the JSON output reflects this -- cf. meta data field `ansible_host_groups`.

In your case, the host is only part of _one_ single ansible host group, i.e, `"ansible_host_groups": "consul_bootstrap"`. Further, the output snippet you have sent does not seem like coming from my script, because it does not fit the JSON format required by Ansible.

So, there's nothing more I can do for you.

**Comment by gvenka008c** [comment]
@lukaspustina Thanks. I am using the openstack.py script from Ansible.

http://docs.ansible.com/ansible/intro_dynamic_inventory.html#example-openstack-external-inventory-script

Is your script the same?

**Comment by gvenka008c** [comment]
@lukaspustina Tried your script but got the below error

```
./openstack.py --list > Output
Traceback (most recent call last):
  File "./openstack.py", line 127, in <module>
    main(sys.argv)
  File "./openstack.py", line 57, in main
    for server in nt.servers.list():
  File "/Library/Python/2.7/site-packages/novaclient/v2/servers.py", line 637, in list
    "servers")
  File "/Library/Python/2.7/site-packages/novaclient/base.py", line 201, in _list
    _resp, body = self.api.client.get(url)
  File "/Library/Python/2.7/site-packages/novaclient/client.py", line 448, in get
    return self._cs_request(url, 'GET', **kwargs)
  File "/Library/Python/2.7/site-packages/novaclient/client.py", line 404, in _cs_request
    self.authenticate()
  File "/Library/Python/2.7/site-packages/novaclient/client.py", line 561, in authenticate
    auth_url = self._v2_auth(auth_url)
  File "/Library/Python/2.7/site-packages/novaclient/client.py", line 652, in _v2_auth
    return self._authenticate(url, body)
  File "/Library/Python/2.7/site-packages/novaclient/client.py", line 667, in _authenticate
    return self._extract_service_catalog(url, resp, respbody)
  File "/Library/Python/2.7/site-packages/novaclient/client.py", line 490, in _extract_service_catalog
    self.management_url = self.get_service_url(self.service_type)
  File "/Library/Python/2.7/site-packages/novaclient/client.py", line 467, in get_service_url
    volume_service_name=self.volume_service_name,)
  File "/Library/Python/2.7/site-packages/novaclient/service_catalog.py", line 87, in url_for
    endpoints=matching_endpoints)
```

**Comment by lukaspustina** [comment]
Hi, sorry for being so blunt: But it seems you don't know what your doing:
1. Of course http://docs.ansible.com/ansible/intro_dynamic_inventory.html#example-openstack-external-inventory-script **is not** my script. It's from the Ansible Team. Look at the GitHub User! just run a `diff`!
2. Why the heck should _my_ script take any parameters? Have you read the Ansible documentation for dynamic inventories -- they are required to work parameterless. Have you actually looked at the source code of my script. There's no argument parsing!
3. My script is called `openstack_inventory.py` in contrast to `openstack.py` from Ansible. So unless you renamed my script, you're actually calling the Ansible's version.

Sorry, but I can't help you.
