### ISSUE TITLE
novaclient.v2.clien

### ISSUE THREAD

**Issue by tapanswain** [lukaspustina/dynamic-inventory-for-ansible-with-openstack#5]
please  change the nova version , nova 1.1 is very old. 

import novaclient.v2.client --

**Comment by lukaspustina** [comment]
Please send me a PR.

**Comment by tapanswain** [comment]
We are seeing this error  
/usr/local/lib/python2.7/dist-packages/novaclient/v1_1/__init__.py:30: UserWarning: Module novaclient.v1_1 is deprecated (taken as a basis for novaclient.v2). The preferable way to get client class or object you can find in novaclient.client module.
  warnings.warn("Module novaclient.v1_1 is deprecated (taken as a basis for "

code-- 
/usr/local/lib/python2.7/dist-packages/novaclient/v1_1/__init__.py 

warnings.warn("Module novaclient.v1_1 is deprecated (taken as a basis for "
              "novaclient.v2). "
              "The preferable way to get client class or object you can find "
              "in novaclient.client module.")

**Comment by lukaspustina** [comment]
We're running OpenStack Icehouse and I only see version 1.1 and version 3 available. Which OpenStack version do you run that offers Nova API version 2?

**Comment by alop** [comment]
The problem is that with newer versions of ansible, novaclient 1.1 is deprecated, and actually there is nothing in novaclient/v1_1/

**Comment by lukaspustina** [comment]
How does novaclient depend on Ansible?

**Comment by alop** [comment]
Ansible actually ships with its own novaclient, so when you run the script independently, you run the system novaclient, but when run from `ansible-playbook -i openstack-inventory.py`, the novaclient loaded is from the ansible distribution
ERROR: Inventory script (openstack_inventory.py) had an execution error: /usr/local/Cellar/ansible/1.9.3/libexec/vendor/lib/python2.7/site-packages/novaclient/v1_1/__init__.py:30: UserWarning: Module novaclient.v1_1 is deprecated (taken as a basis for novaclient.v2). The preferable way to get client class or object you can find in novaclient.client module.
  warnings.warn("Module novaclient.v1_1 is deprecated (taken as a basis for "
Traceback (most recent call last):

**Comment by lukaspustina** [comment]
@alop Ansible does not ship with its own novaclient. It uses the official nova client library as a dependency. So while running the script on Ubuntu 14.04 is still fine, brew, pip etc. pull a more recent version of nova client that yields the described error.
That is fixed now.
