### ISSUE TITLE
Openstack Credentials: missing field

### ISSUE THREAD

**Issue by milaw** [lukaspustina/dynamic-inventory-for-ansible-with-openstack#6]
Hi,

Why are you omitting the OS_TENANT_ID ?
Depending of openstack version, I also need in credentials --os-region-name
Let me know if the below looks like ok for you:

def getOsCredentialsFromEnvironment():
	credentials = {}
	try:
        credentials['VERSION'] = os.environ['OS_COMPUTE_API_VERSION']
		credentials['USERNAME'] = os.environ['OS_USERNAME']
		credentials['PASSWORD'] = os.environ['OS_PASSWORD']
		credentials['TENANT_NAME'] = os.environ['OS_TENANT_NAME']
		credentials['AUTH_URL'] = os.environ['OS_AUTH_URL']
		if os.environ['OS_REGION_NAME']: 
			credentials['REGION'] = os.environ['OS_REGION_NAME']

....

if credentials['REGION']:
    nt = client.Client(credentials['VERSION'], credentials['USERNAME'], credentials['PASSWORD'], os_tenant_name, credentials['AUTH_URL'], credentials['REGION'], service_type="compute")
else:
    nt = client.Client(credentials['VERSION'], credentials['USERNAME'], credentials['PASSWORD'], os_tenant_name, credentials['AUTH_URL'], service_type="compute")

Best,
M.

**Comment by lukaspustina** [comment]
Hi,

well, I'm not _omitting_ `OS_TENANT_ID`; I just don't use it :) But you're right, it might be a sensible addition.

Regarding the region name I agree, but prefer different code. Something like this:
```
credentials['REGION'] = 'regionOne' if not os.environ['OS_REGION_NAME'] else os.environ['OS_REGION_NAME']
...
nt = client.Client(credentials['VERSION'], credentials['USERNAME'], credentials['PASSWORD'], credentials['TENANT_NAME'], credentials['AUTH_URL'], credentials['REGION'], service_type="compute")
```

I hope you get my intention. Just drop me a PR.

Best regards,
Lukas

**Comment by milaw** [comment]
Hi Lukas,

Sorry for the delay.
I worked on your script and made some modifications:
- care list of networks instead of one
- use fixed ip instead of floating ip
- add region name (if relevant)

TODO: add "vars" field under group to care group vars value.

I will update you soon. 

Best,
M.

**Comment by gvenka008c** [comment]
@milaw : Do you have the updated script for the below?

care list of networks instead of one
use fixed ip instead of floating ip
add region name (if relevant)

**Comment by gvenka008c** [comment]
@lukaspustina The script is throwing the below error

./openstack_dynamic_inventory.py
Traceback (most recent call last):
  File "./openstack_dynamic_inventory.py", line 127, in <module>
    main(sys.argv)
  File "./openstack_dynamic_inventory.py", line 52, in main
    nt = client.Client(credentials['VERSION'], credentials['USERNAME'], credentials['PASSWORD'], os_tenant_name, credentials['AUTH_URL'], service_type="compute")
NameError: global name 'os_tenant_name' is not defined

I see all the nova environment details are available.
MacBook-Pro:ansible gvenka008c$ echo $OS_TENANT_NAME
SSD - XPLAT

Please suggest.

**Comment by lukaspustina** [comment]
Come on! That's totally my fault, I messed that up -- Copy & Paste error.

@gvenka008c Please try last commit.

**Comment by gvenka008c** [comment]
@lukaspustina Thanks.
