### ISSUE TITLE
openstack_inventory.py

### ISSUE THREAD

**Issue by gvenka008c** [lukaspustina/dynamic-inventory-for-ansible-with-openstack#8]
@lukaspustina I tried running your script using below command and see the error as UNREACHABLE!. For some reason it is trying to connect to IPv6 address instead of IPv4. Any thoughts?

ansible -i openstack_inventory.py all -m ping -vvvv

2001:558:fc0e:100:f816:3eff:fea9:ce38 ESTABLISH SSH CONNECTION FOR USER: None
2001:558:fc0e:100:f816:3eff:fea9:ce38 SSH: EXEC ssh -C -q -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/Users/gvenka008c/.ansible/cp/ansible-ssh-%h-%p-%r -tt 2001:558:fc0e:100:f816:3eff:fea9:ce38 '( umask 22 && mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1455641594.28-229233455328716 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1455641594.28-229233455328716 )" )'
5db6adfa-76f7-4624-9c0d-179e5777445d | UNREACHABLE! => {
   "changed": false,
   "msg": "ERROR! SSH encountered an unknown error during the connection. We recommend you re-run the command using -vvvv, which will enable SSH debugging output to help diagnose the issue",
   "unreachable": true
}

**Comment by lukaspustina** [comment]
Well, it seems that the inventory has been created correctly. You can verify this by running the script directly and check the JSON document that's printed to stdout.

Regarding your question why IPv6 is used / preferred over IPv4, there are a plethora of possibilities and it depends on your system's configuration. That is out of scope of the dynamic inventory.
