### ISSUE TITLE
Dynamic Inventory

### ISSUE THREAD

**Issue by gvenka008c** [lukaspustina/dynamic-inventory-for-ansible-with-openstack#9]
@lukaspustina Do you have any script that you use to contract your dynamic inventory file? How do you convert the json format output from openstack_inventory.py to build your inventory?

Thanks,
Govind

**Comment by lukaspustina** [comment]
@gvenka008c Hi, sorry for my late response.
I don't understand your first question. For the second question, that's a NOP. Ansible takes the JSON output to create the inventory during runtime -- cf. http://docs.ansible.com/ansible/intro_dynamic_inventory.html.

**Comment by gvenka008c** [comment]
@lukaspustina I have set myid for each server that is provisioned using terraform. How can i access these meta info in my j2 templates? For Ex: Server 1 has my id as 1, server 2 has my id as 2. I want to set this as my zoo id.

**Comment by lukaspustina** [comment]
@gvenka008c You access host variables from a dynamic inventory exactly the same way as you would from a static one.
